### PR TITLE
Refactor test_purification.py

### PR DESCRIPTION
**Pull request by LesterKim**
### Description

- Refactor file to remove duplicate code

### Stakeholder(s)
@Alex-Kolar
@xwu64 
@acbarnett 
@kinetic-cipher
@nikoaliro

### CODE REVIEW

**Comment by xwu64** [comment]
Thanks for your work! I think this organization is great. One suggestion is about the name of node list, like code at here. 

https://github.com/sequence-toolbox/SeQUeNCe/blob/a908a18f20e5a82cd74655c90635ae07fe6afd78/tests/entanglement_management/test_purification.py#L117

Would you like to make the name of this and similar variables more readable, like `node_list` or `nodes`?

**Comment by LesterKim** [comment]
> Thanks for your work! I think this organization is great. One suggestion is about the name of node list, like code at here.
> 
> https://github.com/sequence-toolbox/SeQUeNCe/blob/a908a18f20e5a82cd74655c90635ae07fe6afd78/tests/entanglement_management/test_purification.py#L117
> 
> Would you like to make the name of this and similar variables more readable, like `node_list` or `nodes`?

Yes, I like your suggestion. I'll make an update.

**Comment by LesterKim** [comment]
@xwu64 Let me know if this looks good to merge.

**Comment by caitaozhan** [comment]
This pull request is resolved in pull request #179

**Pull request closed without merging**
